# Koodin Parantaminen Cat-UI:lle Toimivaksi

Tehtävässä 6 opettaja antoi ohjeet koodin parantamiseksi niin, että se integroituu
Cat-UI:n kanssa. Useiden kokeilujen jälkeen tehtiin säätöjä, jotta pikkukuvan
tiedostonimi saatiin käsiteltyä oikein.
`Klikkaa tästä nähdäksesi kuvakaappauksen <uploads/screenshot_03042025.png>`
